apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: dpservice
  namespace: datapower
spec:
  annotations:
    prometheus.io/target: "http://169.46.104.181:30000"
  license:
    accept: true
    use: nonproduction
    license: L-RJON-BYDR3Q
  version: 10.0-cd
  replicas: 1
  resources:	  
    limits:
      memory: 4Gi
    requests:	
      cpu: '1'	      
      memory: 4Gi
  users:
  - name: admin
    passwordSecret: admin-credentials
    accessLevel: privileged
  domains:
  - name: default
    dpApp:
      config:
      - defaultdemo-cfg
 
