apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: dpservice
  namespace: datapower
spec:
  license:
    accept: true
    use: production
    license: L-RJON-BYDR3Q
  version: 10.0-cd
  replicas: 1
  users:
  - name: admin
    passwordSecret: admin-credentials
    accessLevel: privileged
  domains:
  - name: default
    dpApp:
      config:
      - dev-defaultdp-cfg
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi
  
